export const SET_WORD = 'SET_WORD';
export const SET_WINNING_LETTERS = 'SET_WINNING_LETTERS';
export const SET_MESSAGE = 'SET_MESSAGE';
export const SHOW_END_GAME = 'SHOW_END_GAME';
export const SET_MISSED_LETTERS = 'SET_MISSED_LETTERS';
export const RESET_MISSED_LETTERS = 'RESET_MISSED_LETTERS';
export const SET_PLAYED_WORDS = 'SET_PLAYED_WORDS';
